require 'sinatra'
require 'json'

get "/" do
  "Welcome to the Unicorn Cloud Application Platform"
end

get "/info" do
  content_type :json
  '{"name":"vcap","build":2222,"support":"http://support.cloudfoundry.com","version":"0.999","description":"VMwares Cloud Application Platform","allow_debug":false,"frameworks":{"spring":{"name":"spring","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"}],"detection":[{"*.war":true}]},"grails":{"name":"grails","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"}],"detection":[{"*.war":true}]},"node":{"name":"node","runtimes":[{"name":"node","version":"0.4.12","description":"Node.js"},{"name":"node06","version":"0.6.8","description":"Node.js"},{"name":"node08","version":"0.8.2","description":"Node.js"}],"detection":[{"*.js":"."}]},"play":{"name":"play","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"}],"detection":[{"lib/play.*.jar":true}]},"sinatra":{"name":"sinatra","runtimes":[{"name":"ruby18","version":"1.8.7p357","description":"Ruby 1.8"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9"}],"detection":[{"*.rb":true},{"config/environment.rb":false}]},"rails3":{"name":"rails3","runtimes":[{"name":"ruby18","version":"1.8.7p357","description":"Ruby 1.8"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9"}],"detection":[{"config/application.rb":true},{"config/environment.rb":true}]},"lift":{"name":"lift","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"}],"detection":[{"*.war":true}]},"standalone":{"name":"standalone","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"},{"name":"ruby18","version":"1.8.7p357","description":"Ruby 1.8"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9"},{"name":"node","version":"0.4.12","description":"Node.js"},{"name":"node06","version":"0.6.8","description":"Node.js"},{"name":"node08","version":"0.8.2","description":"Node.js"}],"detection":[]},"rack":{"name":"rack","runtimes":[{"name":"ruby18","version":"1.8.7p357","description":"Ruby 1.8"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9"}],"detection":[{"config.ru":true},{"config/environment.rb":false}]},"java_web":{"name":"java_web","runtimes":[{"name":"java","version":"1.6.0_24","description":"Java 6"},{"name":"java7","version":"1.7.0_04","description":"Java 7"}],"detection":[{"*.war":true}]}},"authorization_endpoint":"https://uaa.cloudfoundry.com"}'
end

get "/info/services" do
  content_type :json
  '{"document":{"mongodb":{"2.0":{"id":3,"vendor":"mongodb","version":"2.0","tiers":{"free":{"options":{},"order":1}},"type":"document","description":"MongoDB NoSQL store","provider":null,"default_plan":"free","alias":"current"}}},"database":{"postgresql":{"9.0":{"id":6,"vendor":"postgresql","version":"9.0","tiers":{"free":{"options":{},"order":1}},"type":"database","description":"PostgreSQL database service (vFabric)","provider":null,"default_plan":"free","alias":"current"}},"mysql":{"5.1":{"id":1,"vendor":"mysql","version":"5.1","tiers":{"free":{"options":{},"order":1}},"type":"database","description":"MySQL database service","provider":null,"default_plan":"free","alias":"current"}}},"key-value":{"redis":{"2.2":{"id":2,"vendor":"redis","version":"2.2","tiers":{"free":{"options":{},"order":1}},"type":"key-value","description":"Redis key-value store service","provider":null,"default_plan":"free","alias":"current"}}},"generic":{"rabbitmq":{"2.4":{"id":7,"vendor":"rabbitmq","version":"2.4","tiers":{"free":{"options":{},"order":1}},"type":"generic","description":"RabbitMQ message queue","provider":null,"default_plan":"free","alias":"current"}}}}'
end
